core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', include('django_prometheus.urls')),
    path('health/', include('health_check.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('users/', include(('user.urls', 'user'))),
    path('', include(('home.urls', 'home'))),
    path('menu/', include(('menu.urls', 'menu'))),
    path('media/soal/<str:image_file>', views.soal_media_protect),
    path('media/foto_profile/<str:image_file>', views.profile_foto),
    path('media/sertifikat/<str:image_file>', views.sertifikat_media_protect),
    path('media/pdf/<str:pdf_file>', views.pdf_protect_membership),
    path('media/vidio/<str:vidio_file>', views.vidio_protect_membership),
    path('favicon.ico', views.CachedRedirectView.as_view(url='/static/assets/img/favicon/favicon.ico'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


menu/nilai/models.py
from django.db import models
from user.models import Users
from menu.mapel.models import MataPelajaran
from menu.utils.encode_url import encode_id
import uuid
from django.utils import timezone
# Create your models here.
class Nilai(models.Model):
    choices ={
        "lulus":"lulus",
        "tidak lulus":"tidak lulus"

    }
    id_nilai            = models.BigAutoField(primary_key=True,unique=True,db_index=True)
    user                = models.ForeignKey(Users,on_delete=models.CASCADE,db_index=True)
    mata_pelajaran_obj  = models.ForeignKey(MataPelajaran,on_delete=models.CASCADE,db_index=True,null=True)
    mata_pelajaran      = models.CharField(max_length=100,null=True)
    kelas               = models.CharField(max_length=100,null=True)
    level_study         = models.CharField(max_length=100,null=True)
    nilai               = models.IntegerField()
    predikat            = models.CharField(max_length=2)
    status              = models.CharField(max_length=12,choices=choices)
    tanggal_ujian       = models.DateTimeField(auto_now_add=True,editable=False)

    def save(self, *args, **kwargs):
        if self.level_study:
            self.level_study = self.level_study.strip().lower()
        if self.mata_pelajaran:
            self.mata_pelajaran = self.mata_pelajaran.strip().lower()
        super().save(*args, **kwargs)
    def __str__(self) -> str:
        return f"{self.mata_pelajaran} = {self.nilai}"
    
    def get_id_safe(self):
        return encode_id(self.pk)
    
    class Meta:
        verbose_name_plural = "Nilai"
        ordering = ['mata_pelajaran']
        
class Sertifikat(models.Model):
    no_cert         = models.UUIDField(primary_key=True,unique=True,db_index=True,default=uuid.uuid4)
    nama            = models.CharField(max_length=100)
    tingkat_studi   = models.CharField(max_length=100)
    kelas           = models.CharField(max_length=100,null=True)
    mata_pelajaran  = models.CharField(max_length=100)
    predikat        = models.CharField(max_length=2)
    nilai           = models.IntegerField()
    tanggal_lahir   = models.DateField()
    user            = models.ForeignKey(Users,on_delete=models.CASCADE,blank=True,null=True)
    nilai_obj       = models.OneToOneField(Nilai,on_delete=models.SET_NULL,null=True)
    created_at      = models.DateTimeField(auto_now_add=True,null=True)

    class Meta:
        verbose_name_plural = "Sertifikat"
        
    def get_id_safe(self):
        return encode_id(self.pk)
    
    def __str__(self):
        return f"{self.nama}  -  {self.tingkat_studi}  -  {self.mata_pelajaran}"

menu/ujian/models.py
from django.db import models
from menu.mapel.models import MataPelajaran
from django.core.validators import FileExtensionValidator 
from menu.utils.encode_url import encode_id
import uuid
# Create your models here.
from django_ckeditor_5.fields import CKEditor5Field

class SoalUjian(models.Model):
    choices = {
    "jawaban1":"jawaban_1",
    "jawaban2":"jawaban_2",
    "jawaban3":"jawaban_3",
    "jawaban4":"jawaban_4",
    "jawaban5":"jawaban_5",
    "jawaban6":"jawaban_6",
    "jawaban7":"jawaban_7",
    }
    id_soal     = models.BigAutoField(primary_key=True,unique=True)
    gambar_soal = models.ImageField(upload_to="soal",blank=True,null=True,validators=[FileExtensionValidator(["jpg","png"])])
    soal        = CKEditor5Field('soal', config_name='extends',null=True, blank=True)
    jawaban_1   = CKEditor5Field('jawaban_1', config_name='extends')
    jawaban_2   = CKEditor5Field('jawaban_2', config_name='extends')
    jawaban_3   = CKEditor5Field('jawaban_3', config_name='extends')
    jawaban_4   = CKEditor5Field('jawaban_4', config_name='extends')
    jawaban_5   = CKEditor5Field('jawaban_5', config_name='extends',null=True,blank=True)
    jawaban_6   = CKEditor5Field('jawaban_6', config_name='extends',null=True,blank=True)
    jawaban_7   = CKEditor5Field('jawaban_7', config_name='extends',null=True,blank=True)
    pilih_jawaban_benar = models.CharField(choices=choices,max_length=200)
    mata_pelajaran = models.ForeignKey(MataPelajaran,on_delete=models.CASCADE)   
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.soal
    class Meta:
        verbose_name_plural = "Soal Ujian"
        ordering = ["-created_at"]
    
    def get_id_safe(self):
        return encode_id(self.pk)
    
    @property
    def get_id(self):
        return f"soal__{self.pk}"


menu/ujian/forms.py
from django import forms
from . models import SoalUjian
from django_ckeditor_5.widgets import CKEditor5Widget

class SoalUjianForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SoalUjianForm, self).__init__(*args, **kwargs)
        self.fields['gambar_soal'].widget.attrs['class'] = 'form-control w-100'
        self.fields['jawaban_1'].widget.attrs['class'] = 'form-control '
        self.fields['jawaban_2'].widget.attrs['class'] = 'form-control '
        self.fields['jawaban_3'].widget.attrs['class'] = 'form-control '
        self.fields['jawaban_4'].widget.attrs['class'] = 'form-control '
        self.fields['jawaban_5'].widget.attrs['class'] = 'form-control '
        self.fields['jawaban_6'].widget.attrs['class'] = 'form-control '
        self.fields['jawaban_7'].widget.attrs['class'] = 'form-control '
        self.fields['pilih_jawaban_benar'].widget.attrs['class'] = 'form-select'
        
    def clean(self):
        cleaned_data = super().clean()
        required_fields = ['soal']
        
        for field in required_fields:
            content = cleaned_data.get(field)
            if not content:
                self.add_error(field, f'{field.replace("_", " ").title()} wajib diisi.')
                continue
                
            # Check for empty content
            stripped_content = (content.replace('&nbsp;', '')
                                    .replace('<p></p>', '')
                                    .replace('<p> </p>', '')
                                    .strip())
            if not stripped_content:
                self.add_error(field, f'{field.replace("_", " ").title()} tidak boleh kosong.')
    

    class Meta:
        model = SoalUjian
        exclude = ['mata_pelajaran']
        widgets = {
              "soal": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"}, config_name="extends"
              )
          }

menu/nilai/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import Http404
from menu.nilai.models import Nilai
from menu.mapel.models import MataPelajaran
from menu.levelstudy.models import LevelStudy
from django.contrib.auth.decorators import login_required
from core.utils.decorator import transaksi_settlement_required
from menu.utils.encode_url import decode_id
import qrcode
from io import BytesIO
from django.http import HttpResponse
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from PIL import Image
from reportlab.lib.utils import ImageReader
from django.conf import settings
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from user.models import Profile
from menu.nilai.models import Sertifikat
from menu.utils.encode_url import decode_id
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse
from menu.utils.pagination import pagination_queryset

# Create your views here.

@login_required(login_url='user:masuk')
@transaksi_settlement_required
def daftar_nilai(request):
    custom_range=0
    try:
        if request.user.role in ['pemateri',"admin"]:
            custom_range,nilai_objs=pagination_queryset(request,
                                                        Nilai.objects.all().select_related('sertifikat'),7)
        else:
            custom_range,nilai_objs=pagination_queryset(request,Nilai.objects.filter(
                user=request.user).select_related('sertifikat'),5)
    except Nilai.DoesNotExist:
        pass
    levelstudy_objs = LevelStudy.objects.all()
    context = {
        "nilai_objs": nilai_objs,
        "levelstudy_objs":levelstudy_objs,
        "custom_range":custom_range
    }
    return render(request, 'nilai/nilai.html', context)

@login_required(login_url='user:masuk')
def lakukan_ujian_ulang(request,id_mapel,id_nilai):
    pk_mapel = decode_id(id_mapel)
    pk_nilai = decode_id(id_nilai)
    try:
        mapel_obj = MataPelajaran.objects.get(pk=pk_mapel)
        if request.user.role == "pemateri" or request.user.role == "admin":
            nilai_obj = Nilai.objects.get(pk=pk_nilai,status="tidak lulus",mata_pelajaran_obj=mapel_obj)
            nilai_obj.delete()
            return redirect("menu:daftar-nilai")
        elif request.user.role == "pelajar":
            nilai_obj = Nilai.objects.get(pk=pk_nilai,status="tidak lulus",mata_pelajaran_obj=mapel_obj,user=request.user)
            nilai_obj.delete()
            return redirect("menu:ujian",id_mapel=id_mapel)
    except MataPelajaran.DoesNotExist:
        raise Http404()
    except Nilai.DoesNotExist:
        raise Http404()
    
@login_required(login_url='user:masuk')
def hapus_nilai_ujian(request,id_nilai):
    pk_nilai = decode_id(id_nilai)
    try:
        if request.user.role == "pemateri" or request.user.role == "admin":
            nilai_obj = Nilai.objects.get(pk=pk_nilai,status="tidak lulus")
            nilai_obj.delete()
            return redirect("menu:daftar-nilai")
        elif request.user.role == "pelajar":
            nilai_obj = Nilai.objects.get(pk=pk_nilai,status="tidak lulus",user=request.user)
            nilai_obj.delete()
            return redirect("menu:levelstudy-ujian")
    except MataPelajaran.DoesNotExist:
        raise Http404()
    except Nilai.DoesNotExist:
        raise Http404()

@login_required(login_url='user:masuk')
@transaksi_settlement_required
def daftar_nilai_perlevelstudy(request,id_levelstudy):
    pk = decode_id(id_levelstudy)
    try:
        if request.user.role in ['pemateri',"admin"]:
            nilai_objs = Nilai.objects.filter(mata_pelajaran_obj__level_study__pk=pk).select_related('sertifikat')
        else:
            nilai_objs = Nilai.objects.filter(user=request.user,mata_pelajaran_obj__level_study__pk=pk).select_related('sertifikat')

    except Nilai.DoesNotExist:
        pass
    levelstudy_objs = LevelStudy.objects.all()
    level_study = get_object_or_404(LevelStudy,pk=pk).level_study
    context = {
        "nilai_objs": nilai_objs,
        "levelstudy_objs":levelstudy_objs,
        "level_study":level_study,
        "id_levelstudy":id_levelstudy
    }
    return render(request, 'nilai/nilai.html', context)


def generate_certificate(request,id_sertifikat):
    sertifikat_obj = get_object_or_404(Sertifikat,pk=decode_id(id_sertifikat))
    
    BASE_DIR = settings.BASE_DIR
    image_path = BASE_DIR / 'cert_generator/sertifikat_template.png'

    certificate_image = Image.open(image_path)
    image_width, image_height = certificate_image.size

    buffer = BytesIO()

    pdf = canvas.Canvas(buffer, pagesize=(image_width, image_height))

    pdf.drawImage(image_path, 0, 0, width=image_width, height=image_height)

    font_path1 = BASE_DIR / 'cert_generator/font/LeagueSpartan-Bold.ttf'
    font_path2 = BASE_DIR / 'cert_generator/font/LeagueSpartan-Medium.ttf'
    font_path3 = BASE_DIR / 'cert_generator/font/LeagueSpartan-Regular.ttf'
    pdfmetrics.registerFont(TTFont('LeagueSpartan-Bold', font_path1))
    pdfmetrics.registerFont(TTFont('LeagueSpartan-Medium', font_path2))
    pdfmetrics.registerFont(TTFont('LeagueSpartan-Regular', font_path3))

    nama = str(sertifikat_obj.nama).upper()
    id_cert = str(sertifikat_obj.pk).upper()
    kelas = sertifikat_obj.kelas.upper()
    tingkat_studi = sertifikat_obj.tingkat_studi.upper()
    mata_pelajaran = sertifikat_obj.mata_pelajaran.upper()
    predikat = sertifikat_obj.predikat.upper()
    nilai = sertifikat_obj.nilai
    tanggal_lahir = sertifikat_obj.tanggal_lahir.strftime("%d-%m-%Y")
    tanggal_dibuat = sertifikat_obj.created_at.strftime("%d-%m-%Y")

    positions = {
        "nama": (image_width / 2, 620),
        "id_sertifikat": (550, 715),
        "kelas": (550, 770),
        "tingkat_studi": (550, 830),
        "mata_pelajaran": (550, 890),
        "predikat": (550, 950),
        "nilai": (550, 1010),
        "tanggal_lahir": (550, 1070),
        "tanggal_dibuat": (550, 1130),
    }

    pdf.setFont("LeagueSpartan-Bold", 100)

    nama_width = pdf.stringWidth(nama, "LeagueSpartan-Bold", 100)
    nama_x_position = (image_width - nama_width) / 2 

    pdf.drawString(nama_x_position, image_height - positions['nama'][1], nama)

    pdf.setFont("LeagueSpartan-Regular", 32)

    pdf.drawString(positions['id_sertifikat'][0], image_height - positions['id_sertifikat'][1], "ID SERTIFIKAT")
    pdf.drawString(positions['kelas'][0], image_height - positions['kelas'][1], "KELAS")
    pdf.drawString(positions['tingkat_studi'][0], image_height - positions['tingkat_studi'][1], "TINGKAT STUDI")
    pdf.drawString(positions['mata_pelajaran'][0], image_height - positions['mata_pelajaran'][1], "MATA PELAJARAN")
    pdf.drawString(positions['predikat'][0], image_height - positions['predikat'][1], "PREDIKAT")
    pdf.drawString(positions['nilai'][0], image_height - positions['nilai'][1], "NILAI")
    pdf.drawString(positions['tanggal_lahir'][0], image_height - positions['tanggal_lahir'][1], "TANGGAL LAHIR")
    pdf.drawString(positions['tanggal_dibuat'][0], image_height - positions['tanggal_dibuat'][1], "TANGGAL DIBUAT")

    pdf.drawString(860, image_height - positions['id_sertifikat'][1], ":")
    pdf.drawString(860, image_height - positions['kelas'][1], ":")
    pdf.drawString(860, image_height - positions['tingkat_studi'][1], ":")
    pdf.drawString(860, image_height - positions['mata_pelajaran'][1], ":")
    pdf.drawString(860, image_height - positions['predikat'][1], ":")
    pdf.drawString(860, image_height - positions['nilai'][1], ":")
    pdf.drawString(860, image_height - positions['tanggal_lahir'][1], ":")
    pdf.drawString(860, image_height - positions['tanggal_dibuat'][1], ":")
 
    pdf.drawString(880, image_height - positions['id_sertifikat'][1], f"{id_cert}")
    pdf.drawString(880, image_height - positions['kelas'][1], f"{kelas}")
    pdf.drawString(880, image_height - positions['tingkat_studi'][1], f"{tingkat_studi}")
    pdf.drawString(880, image_height - positions['mata_pelajaran'][1], f"{mata_pelajaran}")
    pdf.drawString(880, image_height - positions['predikat'][1], f"{predikat}")
    pdf.drawString(880, image_height - positions['nilai'][1], f"{nilai}")
    pdf.drawString(880, image_height - positions['tanggal_lahir'][1], f"{tanggal_lahir}")
    pdf.drawString(880, image_height - positions['tanggal_dibuat'][1], f"{tanggal_dibuat}")

    domain = get_current_site(request).domain
    endpoint = reverse("menu:generate-certificate",args=[id_sertifikat])
    protocol = request.scheme
    qr_data = f"{protocol}://{domain}{endpoint}"
    qr_code_image = qrcode.make(qr_data)
    qr_buffer = BytesIO()
    qr_code_image.save(qr_buffer, format='PNG')
    qr_buffer.seek(0)

    qr_image = ImageReader(qr_buffer)

    qr_code_position = (50, 50)
    qr_code_size = 170 

    pdf.drawImage(qr_image, qr_code_position[0], qr_code_position[1], qr_code_size, qr_code_size)
     
    pdf.save()

    buffer.seek(0)

    response = HttpResponse(buffer, content_type='application/pdf')
    response['Content-Disposition'] = 'inline; filenama="certificate_with_qr.pdf"'

    return response


def search_certificate(request):
    id_sertifikat = request.GET.get('id_sertifikat')
    try:
        sertifikat_obj = Sertifikat.objects.get(pk__iexact=id_sertifikat)
    except Sertifikat.DoesNotExist:
        raise Http404()
    
    BASE_DIR = settings.BASE_DIR
    image_path = BASE_DIR / 'cert_generator/sertifikat_template.png'

    certificate_image = Image.open(image_path)
    image_width, image_height = certificate_image.size

    buffer = BytesIO()

    pdf = canvas.Canvas(buffer, pagesize=(image_width, image_height))


menu/ujian/templates/ujian/edit_ujian.html
{% extends "menu_base.html" %}
{% load static %}
{% block title %}ujian{% endblock title %}
{% block style %}{{soal_ujian_forms.media}}{% endblock style %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
<div class="row">
  <div class="col-xxl">
    <div class="card mb-4">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Edit Ujian Soal</h5>
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data" action="{% url "menu:edit-ujian" id_mapel=id_mapel id_soal_ujian=id_soal_ujian %}">
          {% csrf_token %}
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_gambar_soal">Gambar Soal</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.gambar_soal}}
              <small class="text-muted">
                {{ soal_ujian_forms.gambar_soal.errors }}
              </small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_soal">Soal Ujian</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.soal}}
              <small class="text-muted">{{ soal_ujian_forms.soal.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_1">Jawaban 1</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_1}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_1.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_2">Jawaban 2</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_2}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_2.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_3">Jawaban 3</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_3}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_3.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_4">Jawaban 4</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_4}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_4.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_5">Jawaban 5</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_5}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_5.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_6">Jawaban 6</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_6}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_6.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_7">Jawaban 7</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_7}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_7.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_pilih_jawaban_benar">Jawaban Benar</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.pilih_jawaban_benar}}
              <small class="text-muted">{{ soal_ujian_forms.pilih_jawaban_benar.errors }}</small>
            </div>
          </div>
          <div class="row justify-content-end">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Edit</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}
{% block script %}
<script src="{% static "ujian/js/forms.js" %}"></script>
{% endblock script %}

menu/ujian/templates/ujian/tambah_ujian.html
{% extends "menu_base.html" %}
{% block title %}ujian  {% endblock title %}
{% block style %}{{soal_ujian_forms.media}}{% endblock style %}
{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
  <!-- Basic Layout & Basic with Icons -->
<div class="row">
  <!-- Basic Layout -->
  <div class="col-xxl">
    <div class="card mb-4">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Tambah Ujian Soal</h5>
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data" action="{% url "menu:tambah-ujian" id_mapel=id_mapel %}">
          {% csrf_token %}
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_gambar_soal">Gambar Soal</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.gambar_soal}}
              <small class="text-muted">
                {{ soal_ujian_forms.gambar_soal.errors }}
              </small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_soal">Soal Ujian</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.soal}}
              <small class="text-muted">{{ soal_ujian_forms.soal.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_1">Jawaban 1</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_1}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_1.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_2">Jawaban 2</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_2}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_2.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_3">Jawaban 3</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_3}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_3.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_4">Jawaban 4</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_4}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_4.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_5">Jawaban 5</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_5}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_5.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_6">Jawaban 6</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_6}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_6.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_jawaban_7">Jawaban 7</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.jawaban_7}}
              <small class="text-muted">{{ soal_ujian_forms.jawaban_7.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_pilih_jawaban_benar">Jawaban Benar</label>
            <div class="col-sm-10">
              {{soal_ujian_forms.pilih_jawaban_benar}}
              <small class="text-muted">{{ soal_ujian_forms.pilih_jawaban_benar.errors }}</small>
            </div>
          </div>
          <div class="row justify-content-end">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Tambah</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}