core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', include('django_prometheus.urls')),
    path('health/', include('health_check.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('users/', include(('user.urls', 'user'))),
    path('', include(('home.urls', 'home'))),
    path('menu/', include(('menu.urls', 'menu'))),
    path('media/soal/<str:image_file>', views.soal_media_protect),
    path('media/foto_profile/<str:image_file>', views.profile_foto),
    path('media/sertifikat/<str:image_file>', views.sertifikat_media_protect),
    path('media/pdf/<str:pdf_file>', views.pdf_protect_membership),
    path('media/vidio/<str:vidio_file>', views.vidio_protect_membership),
    path('favicon.ico', views.CachedRedirectView.as_view(url='/static/assets/img/favicon/favicon.ico'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


menu/mapel/models.py
from django.db import models
from menu.levelstudy.models import LevelStudy
from menu.utils.encode_url import encode_id
# Create your models here.


class MataPelajaran(models.Model):
    nama_mapel = models.CharField(max_length=20)
    description = models.TextField(max_length=100, blank=True, null=True)
    level_study = models.ForeignKey(LevelStudy,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.pk}. {self.level_study.level_study}-{self.nama_mapel}"
    
   
    class Meta:
        verbose_name_plural = "Mata Pelajaran"
        unique_together = ('nama_mapel', 'level_study')
        ordering = ['-created_at']
    
    def get_id_safe(self):
        return encode_id(self.pk)

menu/modul/models.py
from django.db import models
from menu.mapel.models import MataPelajaran
from django.core.validators import FileExtensionValidator 
from user.models import Users
from django_ckeditor_5.fields import CKEditor5Field
from menu.utils.encode_url import encode_id

# Create your models here.
class Modul(models.Model):
    nama_modul = models.CharField(max_length=50)
    mata_pelajaran = models.ForeignKey(MataPelajaran, on_delete=models.SET_NULL,null=True)
    description = CKEditor5Field('description', config_name='extends',null=True)
    modul = models.FileField(upload_to='pdf',validators=[FileExtensionValidator(allowed_extensions=["pdf"])])
    vidio = models.FileField(upload_to="vidio",validators=[FileExtensionValidator(allowed_extensions=["mp4"])],null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Users,on_delete=models.CASCADE,null=True,blank=True)
    
    def __str__(self):
        return f"{self.nama_modul}"

    class Meta:
        verbose_name_plural = "Modul"
        ordering = ['created_at']
    
    def get_id_safe(self):
        return encode_id(self.pk)
    
class Chat(models.Model):
    user = models.ForeignKey(Users,on_delete=models.CASCADE)
    modul = models.ForeignKey(Modul,on_delete=models.CASCADE)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    

menu/modul/forms.py
from django import forms
from . models import Modul
from django_ckeditor_5.widgets import CKEditor5Widget

class ModulForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ModulForm, self).__init__(*args, **kwargs)
        self.fields['nama_modul'].widget.attrs['class'] = 'form-control'
        self.fields['modul'].widget.attrs['class'] = 'form-control w-100'
        self.fields['vidio'].widget.attrs['class'] = 'form-control w-100'
        self.fields["description"].required = False
    
    class Meta:
        model = Modul
        exclude = ['mata_pelajaran','author']
        widgets = {
              "description": CKEditor5Widget(
                  attrs={"class": "django_ckeditor_5"}, config_name="extends"
              )
          }

menu/modul/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.http import Http404
from django.http import JsonResponse
from .models import MataPelajaran
from .models import Modul
from menu.levelstudy.models import LevelStudy
from config import midtrans
from django.contrib.auth.decorators import login_required
import os
from django.contrib import messages
from .forms import ModulForm
from core.utils.decorator import admin_pemateri_required,transaksi_settlement_required
from menu.utils.encode_url import decode_id
from menu.utils.pagination import pagination_queryset
from .models import Chat
from django.db.models import Count
# Create your views here.
MIDTRANS_CORE = midtrans.MIDTRANS_CORE
PAYMENT_STATUS = midtrans.PAYMENT_STATUS


@login_required(login_url='user:masuk')
@transaksi_settlement_required
def modul_levelstudy(request):
    levelstudy_objs = LevelStudy.objects.annotate(mapel_count=Count('matapelajaran')).order_by("level_study","kelas")
    context = {
        'levelstudy_objs': levelstudy_objs,
    }
    return render(request, 'modul/modul_levelstudy.html', context)


@login_required(login_url='user:masuk')
@transaksi_settlement_required
def modul_mapel(request,id_levelstudy):
    pk =decode_id(id_levelstudy)
    mapel_objs = MataPelajaran.objects.filter(level_study__pk=pk).annotate(modul_count=Count('modul'))
    levelstudy_objs = LevelStudy.objects.get(pk=pk)
    context = {
        'mapel_objs': mapel_objs,
        "id_levelstudy":id_levelstudy,
        "kelas":levelstudy_objs.kelas,
        "level":levelstudy_objs.level_study,
    }
    return render(request, 'modul/modul_mapel.html', context)


@login_required(login_url='user:masuk')
@transaksi_settlement_required
def daftar_modul(request,id_levelstudy, id_mapel):
    pk = decode_id(id_mapel)
    custom_range,modul_objs = pagination_queryset(request,Modul.objects.filter(mata_pelajaran__pk=pk).order_by("nama_modul"),5)
    context = {
        'id_mapel':id_mapel,
        'modul_objs': modul_objs,
        'custom_range':custom_range,
        "id_levelstudy":id_levelstudy
    }
    return render(request, 'modul/daftar_modul.html', context)

@login_required(login_url="user:masuk")
@transaksi_settlement_required
def detailmodul(request,id_levelstudy,id_mapel,id_modul):
    pk_mapel=decode_id(id_mapel)
    pk_modul=decode_id(id_modul)

    try:
        modul_obj = Modul.objects.get(pk=pk_modul,mata_pelajaran__pk=pk_mapel)
    except Modul.DoesNotExist:
        raise Http404
    context = {
        "modul_obj":modul_obj,
        "id_mapel":id_mapel,
        "id_levelstudy":id_levelstudy,
    }
    return render(request,'modul/detail_modul.html',context)

@login_required(login_url='user:masuk')
@admin_pemateri_required
def hapusModul(request,id_levelstudy,id_mapel, id_modul):
    pk_mapel = decode_id(id_mapel)
    pk_modul = decode_id(id_modul)
    try:
        modul_obj = Modul.objects.get(pk=pk_modul)
    except Modul.DoesNotExist:
        return redirect("menu:daftar-modul",id_levelstudy=id_levelstudy,id_mapel=pk_mapel)
    if modul_obj.modul:
        if os.path.isfile(modul_obj.modul.path):
           os.remove(modul_obj.modul.path)
    if modul_obj.vidio:
        if os.path.isfile(modul_obj.vidio.path):
           os.remove(modul_obj.vidio.path)
    messages.success(request,f"selamat modul {modul_obj.nama_modul} berhasil dihapus")
    modul_obj.delete()
    return redirect('menu:daftar-modul',id_levelstudy=id_levelstudy, id_mapel=id_mapel)


@login_required(login_url='user:masuk')
@admin_pemateri_required
def tambah_modul(request,id_levelstudy,id_mapel):
    if request.method == "POST":
        pk = decode_id(id_mapel)
        try:
            mapel_obj = MataPelajaran.objects.get(pk=pk)
        except MataPelajaran.DoesNotExist:
            return JsonResponse({
                "message":"data not a valid",
            })
        modul_forms = ModulForm(request.POST,request.FILES)
        if modul_forms.is_valid():
            nama_modul = modul_forms.cleaned_data['nama_modul']
            description = modul_forms.cleaned_data['description']
            vidio = modul_forms.cleaned_data['vidio']
            modul = modul_forms.cleaned_data['modul']
            Modul.objects.create(
                nama_modul = nama_modul,
                description=description,
                modul = modul,
                mata_pelajaran = mapel_obj,
                author = request.user,
                vidio=vidio,
            ).save()
            messages.success(request,f"selamat modul {nama_modul} berhasil di tambahkan")
            return JsonResponse({
                "message":"data uploaded",
                "id_mapel":id_mapel,
                "id_levelstudy":id_levelstudy,
            })
        else:
            return JsonResponse({
                "data":"cant upload",
                "message":modul_forms.errors.as_text()
            })
    modul_forms = ModulForm(request.POST or None,request.FILES or None)
    context={
        "modul_forms": modul_forms,
        "id_mapel": id_mapel,
        "id_levelstudy":id_levelstudy,
    }
    return render(request, 'modul/tambah_modul.html',context)

@login_required(login_url='user:masuk')
@admin_pemateri_required
def edit_modul(request,id_levelstudy, id_mapel, id_modul):
    pk_modul = decode_id(id_modul)
    if request.user.role not in ["pemateri", "admin"]:
        return redirect("menu:daftar-modul", id_mapel=id_mapel)
    modul_obj = Modul.objects.get(pk=pk_modul)
    if request.method == "POST":
        modul_forms = ModulForm(request.POST, request.FILES, instance=modul_obj)  
        if modul_forms.is_valid():
            modul_forms.save()
            messages.success(request,f"selamat modul {modul_obj.nama_modul} berhasil di edit")
            return JsonResponse({
                "message": "data uploaded",
                "id_mapel": id_mapel,
                "id_levelstudy": id_levelstudy,
            })
        else:
            return JsonResponse({
                "data":"cant upload",
                "message": modul_forms.errors.as_text()
            })
    else:
        modul_forms = ModulForm(instance=modul_obj)
    
    context = {
        "modul_forms": modul_forms,
        "id_mapel": id_mapel,
        "id_modul": id_modul,
        "id_levelstudy": id_levelstudy,
    }
    return render(request, 'modul/edit_modul.html', context)

@login_required(login_url='user:masuk')
@transaksi_settlement_required
def chat(request,id_modul):
    pk = decode_id(id_modul)
    modul_obj = get_object_or_404(Modul,pk=pk)
    chat_objs = Chat.objects.filter(modul=modul_obj)
    context={
        "modul_obj":modul_obj,
        "chat_objs":chat_objs,
        "id_modul":id_modul,
    }
    return render(request,'modul/chat.html',context) 

menu/modul/templates/modul/chat.html
{% extends "menu_base.html" %}
{% load static %}
{% block title %}chat  {% endblock title %}

{% block style %}
<link rel="stylesheet" href="{% static 'modul/css/chat.css' %}">
{% endblock style %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y ">
    <div class="row justify-content-center">
        <div class="text-center mb-4">
            <h3 class="fw-bold">CHAT FORUM</h3>
          </div>
        <div class="col-lg-12">
        <div class="card">
            <div class="card-body d-flex flex-column">
                <div id="chat-messages" class="mb-3" style="max-height: 600px; overflow-y: auto;"> <!-- Increased height -->
                    {% for chat_obj in chat_objs %}
                        <div class="chat-message {% if chat_obj.user == request.user %}sent{% else %}received{% endif %}">
                            <div class="message-header">
                                <span class="user-name">{{ chat_obj.user.full_name }}</span>
                            </div>
                            <div class="message-content">{{ chat_obj.message }}</div>
                            <span class="timestamp {% if chat_obj.user == request.user %}text-white{% endif %}">{{ chat_obj.timestamp|date:"F d, Y H:i" }}</span>
                        </div>
                    {% endfor %}
                </div>
                <div class="input-group">
                    <input type="text" id="message-input" class="form-control" placeholder="Ketik pesan Anda..." autocomplete="off">
                    <div class="input-group-append">
                        <button id="send-button" class="btn btn-primary mx-2" type="button">Kirim</button>
                    </div>
                </div>
                <div id="idModul" data-id={{ id_modul }} ></div>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock content %}


{% block script %}
<script src="{% static "modul/js/chat.js" %}"></script>
{% endblock script %}

menu/modul/templates/modul/daftar_modul.html
{% extends "menu_base.html" %}

{% block title %}modul  {% endblock title %}
{% block content %}

<div class="container-xxl flex-grow-1 container-p-y ">
    <div class="row justify-content-center">
      <div class="col-lg-12">
      <div class="card py-4">
        {% if messages %}
            {% for message in messages %}
            <div id="message" class="container" data-duration="4000">
                <div{% if message.tags %} class="text-center alert alert-{{ message.tags }}"{% endif %}>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <i class="fa-sharp fa-solid fa-triangle-exclamation"></i>
                    {% endif %}
                    {{ message }}
                </div>
            </div>
            {% endfor %}
        {% endif %}
        {% if levelstudy_objs.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for field, errors in levelstudy_objs.errors.items %}
                        <li>{{ field }}: {{ errors|striptags }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <div class="card-header">
          <div><h4 class="mb-3">Modul</h4></div>
          <div>
            <a href="{% url "menu:mapel-modul" id_levelstudy=id_levelstudy %}" class="btn btn-dark text-white"><i class="tf-icon bx bx-chevron-left"></i>Back</a>
            {% if request.user.role == 'admin' or request.user.role == 'pemateri' %}
            <a href="{% url "menu:tambah-modul" id_levelstudy=id_levelstudy id_mapel=id_mapel %}" class="text-white btn btn-primary">Tambah Modul</a>
            {% endif %}
        </div>
        </div>
        <div class="card-body">
            <div class="table-responsive text-nowrap">
                <table class="table table-borderless">
                  <thead>
                    <tr>
                      <th>Nama Modul</th>
                      <th>Deskripsi</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for modul_obj in modul_objs %}
                    <tr>
                      <td>{{modul_obj.nama_modul}}</td>
                      <td>{{modul_obj.description|truncatechars_html:100|safe}}</td>
                      </td>
                      <td>
                        <a href="{% url "menu:detail-modul" id_levelstudy=id_levelstudy id_mapel=id_mapel id_modul=modul_obj.get_id_safe %}" class="btn btn-primary px-3 py-2">Lihat Materi</a>
                        {% if request.user.role == 'admin' or request.user.role == 'pemateri' %}
                        <a href="{% url "menu:edit-modul" id_levelstudy=id_levelstudy id_mapel=id_mapel id_modul=modul_obj.get_id_safe %}" class="btn btn-warning px-3 py-2">Edit </a>
                        <a href="{% url "menu:hapus-modul" id_levelstudy=id_levelstudy id_mapel=id_mapel id_modul=modul_obj.get_id_safe %}" class="btn btn-danger px-3 py-2">Hapus </a>
                        {% endif %}
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                {% include "includes/menu/pagination.html" with queryset=modul_objs custom_range=custom_range %}
              </div>
        </div>
      </div>
    </div>
    </div>
  </div>
{% endblock content %}

menu/modul/templates/modul/detail_modul.html
{% extends "menu_base.html" %}

{% block title %}modul  {% endblock title %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row">
      <div class="col-xl-12">
        <div class="text-center mb-4">
          <h2 class=" fw-bold">DETAIL MODUL</h2>
          <p class="lead text-muted">Berikut ini adalah modul <strong>{{ modul_obj.nama_modul }}</strong> dari mata pelajaran <strong>{{ modul_obj.mata_pelajaran.nama_mapel }}</strong> kelas <strong>{{ modul_obj.mata_pelajaran.level_study.kelas }}</strong> dan level study <strong>{{ modul_obj.mata_pelajaran.level_study.level_study }}</strong></p>
        </div>
        <div class="nav-align-top mb-4">
          <ul class="nav nav-pills mb-3 gap-1" role="tablist">
            <li class="nav-item">
              <a
                href="{% url "menu:daftar-modul" id_levelstudy=id_levelstudy id_mapel=id_mapel %}" 
                class="btn btn-icon btn-dark" style="margin-right:6px;"
              >
              <i class="tf-icon bx bx-chevron-left"></i>
              </a>
            </li>
            <li class="nav-item ">
              <button
                type="button"
                class="nav-link active"
                role="tab"
                data-bs-toggle="tab"
                data-bs-target="#detailmodul"
                aria-controls="detailmodul"
                aria-selected="true"
              >
                Modul
              </button>
            </li>
            <li class="nav-item">
              <button
                type="button"
                class="nav-link"
                role="tab"
                data-bs-toggle="tab"
                data-bs-target="#modulePdf"
                aria-controls="modulePdf"
                aria-selected="false"
              >
                pdf
              </button>
            </li>
            {% if modul_obj.vidio %}
            <li class="nav-item">
              <button
                type="button"
                class="nav-link"
                role="tab"
                data-bs-toggle="tab"
                data-bs-target="#moduleVidio"
                aria-controls="moduleVidio"
                aria-selected="false"
              >
                Vidio
              </button>
            </li>
            {% endif %}
            {% comment %} <li class="nav-item">
              <a href="{% url "menu:modul-chat" id_modul=modul_obj.get_id_safe %}" class="btn btn-icon btn-outline-dark"><i class='bx bx-message-dots' ></i></a>
            </li> {% endcomment %}
          </ul>
          <div class="tab-content">
            <div class="tab-pane fade show active" id="detailmodul" role="tabpanel">
              <h1 class="card-title ">{{ modul_obj.nama_modul }}</h1>
              <p class="card-text" style="text-align:justify;">
                {{ modul_obj.description|safe }}
              </p>
            </div>
            <div class="tab-pane fade" id="modulePdf" role="tabpanel">
              <p>Jika Browser Anda tidak mendukung PDF inline. Silakan <a href="{{ modul_obj.modul.url }}">lihat PDF</a> untuk melihatnya.</p>
              <object data="{{ modul_obj.modul.url }}" type="application/pdf" width="100%" height="600px">
              </object>
            </div>
            {% if modul_obj.vidio %}
            <div class="tab-pane fade" id="moduleVidio" role="tabpanel">
              <p>Jika Browser anda Tidak mendukung <a href="{{ modul_obj.vidio.url }}">lihat Vidio</a> untuk melihatnya.</p>
              <div id="trailer" class="section d-flex justify-content-center">
                <div class="ratio ratio-16x9" style="max-width: 100%;">
                  <video id="videoPlayer" class="embed-responsive-item" controls>
                    <source src="{{modul_obj.vidio.url}}" type="video/mp4">
                  </video>
                </div>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}


menu/modul/templates/modul/edit_modul.html
{% extends "menu_base.html" %}
{% load static %}
{% block title %}modul  {% endblock title %}
{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
  <!-- Basic Layout & Basic with Icons -->
<div class="row">
  <!-- Basic Layout -->
  <div class="col-xxl">
    <div class="card mb-4">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Edit Modul</h5>
      </div>
      <div class="card-body">
        <div id="feedbackMessage" class="text-center mt-3"></div> <!-- Feedback Message -->
        <form method="post" action="{% url 'menu:edit-modul' id_levelstudy=id_levelstudy id_mapel=id_mapel id_modul=id_modul %}" enctype="multipart/form-data" id="upload_form">
          {% csrf_token %}
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_nama_modul">Nama Modul</label>
            <div class="col-sm-10">
              {{ modul_forms.nama_modul }}
              <small class="text-muted">{{ modul_forms.nama_modul.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_description">Description</label>
            <div class="col-sm-10">
              {{ modul_forms.description }}
              {{ modul_forms.media }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_modul">Modul File</label>
            <div id="id-input" data-input="{{modul_forms.modul.id_for_label}}" style="display:none;"></div>
            <div class="col-sm-10">
              {{ modul_forms.modul }}
              {{ modul_forms.modul.errors }}
              <small class="text-mute">Harap Untuk tidak mengupload file lebih dari 100 mb</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_vidio">Vidio</label>
            <div class="col-sm-10">
              {{ modul_forms.vidio }}
              {{ modul_forms.vidio.errors }}
              <small class="text-mute">Harap Untuk tidak mengupload file lebih dari 300 mb</small>
            </div>
          </div>
          <div class="row justify-content-end">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Edit</button>
              <a href="{% url "menu:daftar-modul" id_levelstudy=id_levelstudy id_mapel=id_mapel %}" class="btn btn-outline-dark">Kembali</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="progressModal" tabindex="-1" aria-labelledby="progressModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="progressModalLabel">Uploading...</h5>
      </div>
      <div class="modal-body">
        <div class="progress progress-md portfolio-progress">
          <!-- Progress bar yang telah disesuaikan -->
          <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div id="progressText" class="text-center mt-2">0%</div> <!-- Update text sesuai dengan progress bar -->
        <button type="button" class="btn btn-danger mt-3" id="cancelButton">Cancel</button>
      </div>
    </div>
  </div>
</div>
<script src="{% static "modul/internal/progressbar.js" %}"></script>
{% endblock content %}

menu/modul/templates/modul/modul_levelstudy.html
{% extends "menu_base.html" %}

{% block title %}Modul{% endblock title %}

{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
  <div class="text-center mb-4">
    <h1 class="display-4 fw-bold">LEVEL STUDY</h1>
    <p class="lead text-muted">Pilih level studi yang sesuai untuk memulai membaca modul</p>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-12 order-1">
      <div class="row g-3">
        {% for levelstudy_obj in levelstudy_objs %}
          <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
            <div class="card h-100 border-0 rounded ">
              <div class="card-body d-flex flex-column justify-content-between">
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <div class="d-flex align-items-center">
                    <div class="icon-circle bg-primary text-white rounded-circle d-flex align-items-center justify-content-center me-3" style="width: 50px; height: 50px;">
                      <i class="bx bx-book fs-3"></i>
                    </div>
                    <div>
                      <h5 class="mb-0 fw-bold" style="font-size: 1.25rem;">{{ levelstudy_obj.level_study }}</h5>
                      <small class="text-muted" style="font-size: 0.9rem;">Kelas {{ levelstudy_obj.kelas }}</small>
                    </div>
                  </div>
                  <span class="badge bg-label-info text-dark rounded-pill">{{ levelstudy_obj.mapel_count }} Mapel</span>
                </div>
                <div class="text-center mt-auto">
                  <a href="{% url 'menu:mapel-modul' id_levelstudy=levelstudy_obj.get_id_safe %}" 
                     class="btn btn-outline-primary btn-sm rounded-pill mt-3">
                    <i class="bx bx-right-arrow-alt me-1"></i> Kunjungi
                  </a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

menu/modul/templates/modul/tambah_modul.html
{% extends "menu_base.html" %}
{% load static %}
{% block title %}modul  {% endblock title %}
{% block content %}
<div class="container-xxl flex-grow-1 container-p-y">
  <!-- Basic Layout & Basic with Icons -->
<div class="row">
  <!-- Basic Layout -->
  <div class="col-xxl">
    <div class="card mb-4">
      <div class="card-header d-flex align-items-center justify-content-between">
        <h5 class="mb-0">Tambah Modul</h5>
      </div>
      <div class="card-body">
        <div id="feedbackMessage" class="text-center mt-3"></div> <!-- Feedback Message -->
        <form method="post" action="{% url 'menu:tambah-modul' id_levelstudy=id_levelstudy id_mapel=id_mapel %}" enctype="multipart/form-data" id="upload_form">
          {% csrf_token %}
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_nama_modul">Nama Modul</label>
            <div class="col-sm-10">
              {{ modul_forms.nama_modul }}
              <small class="text-muted">{{ modul_forms.nama_modul.errors }}</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_description">Description</label>
            <div class="col-sm-10">
              {{ modul_forms.description }}
              {{ modul_forms.media }}
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_modul">Modul File</label>
            <div id="id-input" data-input="{{modul_forms.modul.id_for_label}}" style="display:none;"></div>
            <div class="col-sm-10">
              {{ modul_forms.modul }}
              {{ modul_forms.modul.errors }}
              <small class="text-mute">Harap Untuk tidak mengupload file lebih dari 100 mb</small>
            </div>
          </div>
          <div class="row mb-3">
            <label class="col-sm-2 col-form-label" for="id_vidio">Vidio</label>
            <div class="col-sm-10">
              {{ modul_forms.vidio }}
              {{ modul_forms.vidio.errors }}
              <small class="text-mute">Harap Untuk tidak mengupload file lebih dari 300 mb</small>
            </div>
          </div>
          <div class="row justify-content-end">
            <div class="col-sm-10">
              <button type="submit" class="btn btn-primary">Tambah</button>
              <a href="{% url "menu:daftar-modul" id_levelstudy=id_levelstudy id_mapel=id_mapel %}" class="btn btn-outline-dark">Kembali</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="progressModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="progressModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="progressModalLabel">Uploading...</h5>
      </div>
      <div class="modal-body">
        <div class="progress progress-md portfolio-progress">
          <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
        <div id="progressText" class="text-center mt-2">0%</div>
        <button type="button" class="btn btn-danger mt-3" id="cancelButton">Cancel</button>
      </div>
    </div>
  </div>
</div>
<script src="{% static "modul/internal/progressbar.js" %}"></script>
{% endblock content %}