core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', include('django_prometheus.urls')),
    path('health/', include('health_check.urls')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('users/', include(('user.urls', 'user'))),
    path('', include(('home.urls', 'home'))),
    path('menu/', include(('menu.urls', 'menu'))),
    path('media/soal/<str:image_file>', views.soal_media_protect),
    path('media/foto_profile/<str:image_file>', views.profile_foto),
    path('media/sertifikat/<str:image_file>', views.sertifikat_media_protect),
    path('media/pdf/<str:pdf_file>', views.pdf_protect_membership),
    path('media/vidio/<str:vidio_file>', views.vidio_protect_membership),
    path('favicon.ico', views.CachedRedirectView.as_view(url='/static/assets/img/favicon/favicon.ico'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('masuk/',views.masuk,name='masuk'),
    path('keluar/',views.keluar,name='keluar'),
    path('daftar/',views.daftar,name='daftar'),
    path('aktifasi/<str:uidb64>/<str:token>/',views.aktifasi,name='aktifasi'),
    path('lupa-password/', views.lupaPassword, name='lupapassword'),
    path('resetpassword/<str:uidb64>/<str:token>/', views.resetPassword, name='resetpassword'),
    path('ubah-password/', views.UbahPasswordView.as_view(), name='ubah_password'),
    path('add-profile/', views.add_profile, name='add-profile'),
]

user/models.py
from django.contrib.auth.models import AbstractUser,PermissionsMixin
from django.db import models
from django.utils.translation import gettext as _
from .managers import CustomUserManager
import uuid

from django.core.files.base import ContentFile
from PIL import Image as PILImage
import io
import os

class Users(AbstractUser,PermissionsMixin):
    ROLE = (
        ('pelajar', 'Pelajar'),
        ('pemateri', 'Pemateri'),
        ('admin', 'Admin'),
    )
    id              = None
    username        = None
    first_name      = None
    last_name       = None

    
    id_user         = models.UUIDField(default=uuid.uuid4,primary_key=True,unique=True)
    full_name       = models.CharField(_("full name"), max_length=50)
    email           = models.EmailField(_("email"), unique=True)
    role            = models.CharField(_("role"), max_length=50, choices=ROLE, default='pelajar',help_text=_("To enter the Django dashboard, change to admin or pemateri"),)
    is_active       = models.BooleanField(default=False)
    waktu_aktifasi  = models.DateTimeField(blank=True,null=True)
    last_password_reset_request = models.DateTimeField(null=True, blank=True)
    
    USERNAME_FIELD  = "email"
    REQUIRED_FIELDS = ["full_name"]

    objects = CustomUserManager()

    def __str__(self):
        return self.email
      
            
    def save(self, *args, **kwargs):
        if self.role == 'admin':
            self.is_staff = True
            self.is_superuser = True
        elif self.role != 'admin':
            self.is_staff = False
            self.is_superuser = False
        if self.role == 'pemateri':
            self.is_staff = True
        super().save(*args, **kwargs)
        
        
class Token(models.Model):
    user                    = models.ForeignKey(Users,on_delete=models.CASCADE)  
    token                   = models.CharField(max_length=100,blank=True,null=True)
    is_created              = models.BooleanField(default=False)
    created_at              = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.user}"
    

class ActiveSession(models.Model):
    user = models.OneToOneField(Users, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)


class Profile(models.Model):
    JENIS_KELAMIN = (
        ('pria', 'Pria'),
        ('wanita', 'Wanita'),
    )
    user            = models.OneToOneField(Users,on_delete=models.CASCADE)
    nama_lengkap    = models.CharField(max_length=100)
    foto            = models.ImageField(upload_to="foto_profile",null=True)
    jenis_kelamin   = models.CharField(max_length=10,choices=JENIS_KELAMIN,null=True)
    tempat_tinggal  = models.CharField(max_length=40,null=True)
    nomor_telepon   = models.CharField(max_length=14,null=True)
    tanggal_lahir   = models.DateField(null=True)
    created_at      = models.DateTimeField(auto_now_add=True)
    updated_at      = models.DateTimeField(auto_now=True)
    

    def __str__(self):
        return f"{self.nama_lengkap}"

user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.forms import PasswordChangeForm
from .models import Users,Profile


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = Users
        fields = ("email",'full_name')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = Users
        fields = ("email",'full_name')




class ChangePasswordForm(PasswordChangeForm):
   
    def clean(self):
        cleaned_data = super().clean()
        old_password = cleaned_data.get("old_password")
        new_password1 = cleaned_data.get("new_password1")
        new_password2 = cleaned_data.get("new_password2")

        
        if old_password == new_password1 and old_password == new_password2:
            raise forms.ValidationError("Kata sandi tidak boleh sama dengan sebelumnya")

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['class'] = 'form-control w-100 '

class AddProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddProfileForm, self).__init__(*args, **kwargs)
        self.fields['nama_lengkap'].widget.attrs['class'] = 'form-control'
        self.fields['jenis_kelamin'].widget.attrs['class'] = 'form-select'
        self.fields['tempat_tinggal'].widget.attrs['class'] = 'form-control w-100'
        self.fields['foto'].widget.attrs['class'] = 'form-control w-100'
        self.fields['nomor_telepon'].widget.attrs['class'] = 'form-control w-100'
        self.fields['nomor_telepon'].widget.attrs['class'] = 'form-control w-100'
        self.fields['tanggal_lahir'].widget.attrs['class'] = 'form-control'

    
    class Meta:
        model = Profile
        exclude = ["user"]
        widgets = {
              "tanggal_lahir": forms.DateInput(format="%Y-%m-%d", attrs={"type": "date"})
          }

user/views.py
from django.shortcuts import render, redirect
from django.http.response import Http404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .models import Users,Profile
from django.core.validators import validate_email
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from http import HTTPStatus
from django.urls import reverse,reverse_lazy
from django.utils.translation import gettext as _
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from .utils.kirim_email import kirim_email_activate, kirim_email_reset_password
from .token import account_activation_token
from django.utils import timezone
import requests
from .forms import ChangePasswordForm,AddProfileForm
from django.contrib.auth.views import PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.decorators import login_required
from datetime import timedelta
from django.core.cache import cache

# Create your views here.
def daftar(request):
    # jika request adalah post
    if request.method == 'POST':
        full_name = request.POST['full_name']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        if not full_name.strip() or len(full_name) != len(full_name.strip()):
            messages.error(request, _("Full name is invalid"))
            return render(request, 'user/daftar.html', status=HTTPStatus.BAD_REQUEST)

        cleaned_full_name = str(full_name).split()
        cleaned_full_name = ' '.join(cleaned_full_name)
        if len(full_name) != len(cleaned_full_name):
            messages.error(request, _("The full name has too many spaces"))
            return render(request, 'user/daftar.html', status=HTTPStatus.BAD_REQUEST)

        try:
            validate_email(email)
        except ValidationError:
            messages.error(request, _('Invalid email address'))
            return render(request, 'user/daftar.html', status=HTTPStatus.BAD_REQUEST)

        if password1 != password2:
            messages.error(request, _('Different Passwords'))
            return render(request, 'user/daftar.html', status=HTTPStatus.BAD_REQUEST)

        
        if str(password1).isspace() or len(password1) < 1 and str(password2).isspace() or len(password2) < 1:
            messages.error(request, _(
                "Password cannot contain spaces or be empty"))
            return render(request, 'user/daftar.html', status=HTTPStatus.BAD_REQUEST)

        # validasi password
        try:
            validate_password(password1)
        except ValidationError as e:
            messages.error(request, '\n '.join(e))
            return render(request, 'user/daftar.html', status=HTTPStatus.BAD_REQUEST)

        # validasi apakah email telah digunakan

        if Users.objects.filter(email=email.lower()).exists():
            messages.error(request, _("User with email already exists"))
            return render(request, 'user/daftar.html', status=HTTPStatus.BAD_REQUEST)

        # kalau semua validasi lolos maka user dibuat
        user_obj = Users.objects.create_user(
            full_name=cleaned_full_name,
            email=email.lower(),
            password=password1
        )

        uid = urlsafe_base64_encode(force_bytes(user_obj.pk))
        token = account_activation_token.make_token(user_obj)        
        domain = get_current_site(request).domain
        protocol = request.is_secure() and "https" or "http"
        # Kirim email secara asinkronus dengan domain dan protocol sebagai argumen
        kirim_email_activate.delay(uid, token, user_obj.email.lower(), domain, protocol)
        url = reverse("user:masuk")
        return redirect(url+f"?command=verification&email={email}")

    if request.method == "GET":
        if request.user.is_authenticated:
            return redirect("home:home")
        return render(request, 'user/daftar.html', status=HTTPStatus.OK)


def aktifasi(request, uidb64, token):
    if request.user.is_authenticated:
        return redirect("home:home")
    # decode uidb64 lalu dijadikan pk atau id asli
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user_obj = Users._default_manager.get(pk=uid)
    except Exception:
        messages.error(request, 'Link Token tidak valid.')
        return redirect("user:daftar")

    if account_activation_token.check_token(user_obj, token):
        # Pastikan token belum digunakan sebelumnya
        user_obj.is_active = True
        user_obj.waktu_aktifasi = timezone.now()
        user_obj.save()
        messages.success(
            request, f"Selamat {user_obj.full_name}, akunmu telah aktif.")
        return redirect('user:masuk')
    else:
        messages.error(request, 'Link Token tidak valid.')
        return redirect("user:masuk")


def masuk(request):
    if request.user.is_authenticated:
        return redirect("home:home")  # response 302

    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        try:
            user_obj = Users.objects.get(email=email.lower(), is_active=False)
            if user_obj:
                messages.error(request, 'Silahkan aktivasi akun melalui email. hubungi admin jika belum mendapatkan token')
                return render(request, 'user/masuk.html', status=HTTPStatus.UNAUTHORIZED)
        except Users.DoesNotExist:
            pass

        user = authenticate(request, email=email.lower(), password=password)
        # jika email dan password benar atau ada
        if user is not None:
            login(request, user)
            url = request.META.get("HTTP_REFERER")
            try:
                query = requests.utils.urlparse(url).query
                params = dict(
                    x.split("=") for x in query.split("&")
                )
                if "next" in params:
                    nextPage = params["next"]
                    return redirect(nextPage)
            except:
                return redirect("home:home")  # response 302
        # jika email salah ataupun password salah
        else:
            try:
                url = request.META.get("HTTP_REFERER")
                query = requests.utils.urlparse(url).query
                params =dict(
                    x.split("=") for x in query.split("&")
                )
                if "next" in params:
                    nextPage = params["next"]
                    messages.error(request, 'Email Atau Password Salah')
                    return redirect(nextPage)
            except:
                messages.error(request, 'Email Atau Password Salah')
                return render(request, 'user/masuk.html', status=HTTPStatus.UNAUTHORIZED)
    else:
        return render(request, 'user/masuk.html', status=HTTPStatus.OK)


def keluar(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect("user:masuk")
    raise Http404()


def lupaPassword(request):
    if request.method == "POST":
        email = request.POST['email']
        try:
            user_obj = Users.objects.get(email=email.lower())
            if user_obj:
                now = timezone.now()
                if user_obj.last_password_reset_request:
                    time_since_last_request = now - user_obj.last_password_reset_request
                    remaining_time = timedelta(minutes=2) - time_since_last_request

                    if remaining_time > timedelta(0):
                        # Jika waktu tunda belum berlalu
                        seconds_remaining = int(remaining_time.total_seconds())
                        minutes_remaining, seconds_remaining = divmod(seconds_remaining, 60)
                        messages.error(request, f"kamu harus menunggu {minutes_remaining} menit dan {seconds_remaining} detik sebelum melakukan request kembali.")
                        return render(request, 'user/lupapassword.html')

                user_obj.last_password_reset_request = now
                user_obj.save()

                uid = urlsafe_base64_encode(force_bytes(user_obj.id_user))
                token = default_token_generator.make_token(user_obj)
                kirim_email_reset_password.delay(
                    uid=uid,
                    token=token,
                    user_obj_email=email,
                    domain=request.get_host(),
                    protocol=request.scheme
                )
                url = reverse("user:lupapassword")
                return redirect(url+f"?command=verification&email={email}")

        except Users.DoesNotExist:
            messages.error(request, 'Akun Tidak Ditemukan')
            return render(request, 'user/lupapassword.html', status=HTTPStatus.UNAUTHORIZED)
    else:
        if request.user.is_authenticated:
            return redirect("home:home")
        return render(request, 'user/lupapassword.html')

def resetPassword(request, uidb64, token):
    if request.method == "GET":
        if request.user.is_authenticated:
            logout(request)
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user_obj = Users._default_manager.get(pk=uid)
        except Exception:
            messages.error(request, 'Link Token tidak valid')
            return redirect("user:masuk")

        if default_token_generator.check_token(user_obj, token):
            return render(request, 'user/resetpassword.html', {"uid": uidb64, "token": token})
        else:

user/templates/user/addprofile.html
{% extends "menu_base.html" %}
{% load static %}

{% block title %}account  {% endblock title %}

{% block content %}
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Account Settings /</span> Account</h4>
  <div class="row">
    <div class="col-md-12">
      {% include "includes/menu/auth/navigasi_account.html" %}
      <div class="card mb-4">
        <h5 class="card-header">Profile Details</h5>
        <!-- Account -->
        {% if messages %}
          {% for message in messages %}
          <div id="message" class="container" data-duration="8000">
              <div{% if message.tags %} class="text-center alert alert-{{ message.tags }}"{% endif %}>
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                  <i class="fa-sharp fa-solid fa-triangle-exclamation"></i>
                  {% endif %}
                  {{ message }}
              </div>
          </div>
          {% endfor %}
        {% endif %}
        <hr class="my-0" />
        <div class="card-body">
          <form id="formAccountSettings" method="POST" action="{% url "user:add-profile" %}" enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="row">
              <div class="mb-3 col-md-6">
                <label for="id_nama_lengkap" class="form-label">Nama Lengkap</label>
                {{ forms.nama_lengkap }}
              </div>
              <div class="mb-3 col-md-6">
                <label for="id_foto" class="form-label">Foto</label>
                {{ forms.foto }}
              </div>
              <div class="mb-3 col-md-6">
                <label for="id_jenis_kelamin" class="form-label">Jenis Kelamin</label>
              {{ forms.jenis_kelamin }}
              </div>
              <div class="mb-3 col-md-6">
                <label for="id_tempat_tinggal" class="form-label">Tempat Tinggal</label>
              {{ forms.tempat_tinggal }}
              </div>
              <div class="mb-3 col-md-6">
                <label for="id_nomor_telepon" class="form-label">No telepon</label>
              {{ forms.nomor_telepon }}
              </div>
              <div class="mb-3 col-md-6">
                <label for="id_tanggal_lahir" class="form-label">Tanggal Lahir</label>
              {{ forms.tanggal_lahir }}
              </div>
            <div class="mt-2">
              <button type="submit" class="btn btn-primary me-2">Save changes</button>
              <button type="reset" class="btn btn-outline-secondary">Reset Form</button>
            </div>
          </form>
        </div>
        <!-- /Account -->
      </div>
    </div>
  </div>
</div>
<!-- / Content -->
{% endblock content %}

user/templates/user/daftar.html
{% extends "auth_base.html" %}
{% block title %}daftar  {% endblock title %}
{% block title_form %}
{% if request.GET.command != 'verification' %}
Daftar
{% endif %}
{% endblock title_form %}

{% block form %}
{% if request.GET.command == 'verification' %}
<div class="alert" role="alert">
    <p>
        Trimakasih telah mendaftar. verifikasi telah dikirim melalui email [{{request.GET.email}}] Mungkin saja email yang dikirim berada di spam pada email anda Masuk? <a href="{% url 'user:masuk' %}">Login</a>
    </p>
</div>
{% else %}
<form id="formAuthentication" class="mb-3" action="{% url "user:daftar" %}" method="POST">
  {% csrf_token %}
    <div class="mb-3">
      <label for="full_name" class="form-label">Full Name</label>
      <input
        type="text"
        class="form-control"
        id="full_name"
        name="full_name"
        placeholder="Enter your full name"
        autofocus
        required
      />
    </div>
   
    <div class="mb-3">
      <label for="email" class="form-label">Email</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter your email"
        autofocus
        required
      />
    </div>
   
    <div class="mb-3 form-password-toggle">
      <label class="form-label" for="password1">Password</label>
      <div class="input-group input-group-merge">
        <input
          type="password"
          id="password1"
          class="form-control"
          name="password1"
          placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
          aria-describedby="password"
          required
        />
        <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
      </div>
    </div>

    <div class="mb-3 form-password-toggle">
      <label class="form-label" for="password2">Password Confirmation</label>
      <div class="input-group input-group-merge">
        <input
          type="password"
          id="password2"
          class="form-control"
          name="password2"
          placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
          aria-describedby="password"
          required
        />
        <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
      </div>
    </div>
    <button class="btn btn-primary d-grid w-100">Daftar</button>
  </form>
  <p class="text-center">
    <span>Sudah punya akun?</span>
    <a href="{% url "user:masuk" %}">
      <span>Masuk</span>
    </a>
  </p>
<div class="d-flex w-100 justify-content-center">
  {% include "includes/auth/error_message.html" %}
</div>

{% endif %}
{% endblock form %}

user/templates/user/lupapassword.html
{% extends "auth_base.html" %}
{% block title %}lupa password  {% endblock title %}
{% block title_form %}
{% if request.GET.command != 'verification' %}
Lupa Password
{% endif %}
{% endblock title_form %}

{% block form %}
{% if request.GET.command == 'verification' %}
<div class="alert" role="alert">
    <p>
        Trimakasih telah mendaftar. verifikasi telah dikirim melalui email [{{request.GET.email}}] Mungkin saja email yang dikirim berada di spam pada email anda Masuk? <a href="{% url 'user:masuk' %}">Login</a>
    </p>
</div>
{% else %}
<form id="formAuthentication" class="mb-3" action="{% url "user:lupapassword" %}" method="POST">
  {% csrf_token %}
  
  <div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter your email "
      autofocus
      required
    />
  </div>
  <div class="mb-3">
    <button class="btn btn-primary d-grid w-100" type="submit">Submit</button>
  </div>
</form>
<div class="text-center">
    <a href="{% url "user:masuk" %}" class="d-flex align-items-center justify-content-center">
      <i class="bx bx-chevron-left scaleX-n1-rtl bx-sm"></i>
      Back to login
    </a>
  </div>
<div class="d-flex w-100 justify-content-center">
  {% include "includes/auth/error_message.html" %}
</div>

{% endif %}
{% endblock form %}

user/templates/user/masuk.html
{% extends "auth_base.html" %}
{% block title %}masuk  {% endblock title %}

{% block title_form %}
{% if request.GET.command != 'verification' %}
Masuk
{% endif %}
{% endblock title_form %}

{% block form %}
{% if request.GET.command == 'verification' %}
<div class="alert" role="alert">
    <p>
        Trimakasih telah mendaftar. verifikasi telah dikirim melalui email [{{request.GET.email}}] Mungkin saja email yang dikirim berada di spam pada email anda Masuk? <a href="{% url 'user:masuk' %}">Login</a>
    </p>
</div>
{% else %}
<form id="formAuthentication" class="mb-3" action="{% url "user:masuk" %}" method="POST">
  {% csrf_token %}
  
  <div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter your email "
      autofocus
      required
    />
  </div>
  <div class="mb-3 form-password-toggle">
    <div class="d-flex justify-content-between">
      <label class="form-label" for="password">Password</label>
      <a href="{% url "user:lupapassword" %}">
        <small>Forgot Password?</small>
      </a>
    </div>
    <div class="input-group input-group-merge">
      <input
        type="password"
        id="password"
        class="form-control"
        name="password"
        placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
        aria-describedby="password"
        required
      />
      <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
    </div>
  </div>
  <div class="mb-3">
    <button class="btn btn-primary d-grid w-100" type="submit">masuk</button>
  </div>
</form>
<p class="text-center">
  <span>Belum mendaftar?</span>
  <a href="{% url "user:daftar" %}">
    <span>Daftar</span>
  </a>
</p>
<div class="d-flex w-100 justify-content-center">
  {% include "includes/auth/error_message.html" %}
</div>

{% endif %}
{% endblock form %}

user/templates/user/resetpassword.html
{% extends "auth_base.html" %}
{% block title %}reset pasword  {% endblock title %}

{% block title_form %}
{% if request.GET.command != 'verification' %}
Reset Password
{% endif %}
{% endblock title_form %}

{% block form %}
<form id="formAuthentication" class="mb-3" action="{% url "user:resetpassword" uidb64=uid token=token %}" method="POST">
  {% csrf_token %}
  
  <div class="mb-3 form-password-toggle">
    <div class="d-flex justify-content-between">
      <label class="form-label" for="password1">Password</label>
    </div>
    <div class="input-group input-group-merge">
      <input
        type="password"
        id="password1"
        class="form-control"
        name="password1"
        placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
        aria-describedby="password"
        required
      />
      <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
    </div>
  </div>
  <div class="mb-3 form-password-toggle">
    <div class="d-flex justify-content-between">
      <label class="form-label" for="password2">Password Confirmation</label>
    </div>
    <div class="input-group input-group-merge">
      <input
        type="password"
        id="password2"
        class="form-control"
        name="password2"
        placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
        aria-describedby="password"
        required
      />
      <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
    </div>
  </div>
  <div class="mb-3">
    <button class="btn btn-primary d-grid w-100" type="submit">Reset Password</button>
  </div>
</form>
<div class="text-center">
    <a href="{% url "user:masuk" %}" class="d-flex align-items-center justify-content-center">
      <i class="bx bx-chevron-left scaleX-n1-rtl bx-sm"></i>
      Back to login
    </a>
  </div>
<div class="d-flex w-100 justify-content-center">
  {% include "includes/auth/error_message.html" %}
</div>
{% endblock form %}

user/templates/user/ubah_password.html
{% extends "menu_base.html" %}
{% load static %}

{% block title %}account  {% endblock title %}

{% block content %}
<!-- Content -->

<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Account Settings /</span> Account</h4>
  <div class="row">
    <div class="col-md-12">
      {% include "includes/menu/auth/navigasi_account.html" %}
      <div class="card mb-4">
        <!-- Account -->
        {% if messages %}
          {% for message in messages %}
          <div id="message" class="container" data-duration="4000">
              <div{% if message.tags %} class="text-center alert alert-{{ message.tags }}"{% endif %}>
                  {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                  <i class="fa-sharp fa-solid fa-triangle-exclamation"></i>
                  {% endif %}
                  {{ message }}
              </div>
          </div>
          {% endfor %}
        {% endif %}
        <hr class="my-0" />
        <div class="card-body">
          <form id="formAccountSettings" method="POST">
            {% csrf_token %}
            <div class="row">
              <div class="mb-3 col-md-12">
                <label for="{{ form.old_password.id_for_label }}" class="form-label">{{form.old_password.label}}</label>
                {{ form.old_password }}
                <small class="text-muted">{{ form.old_password.errors }}</small>
                <small class="form-text text-muted">{{ form.old_password.help_text }}</small>
              </div>
              <div class="mb-3 col-md-12">
                <label for="{{ form.new_password1.id_for_label }}">{{form.new_password1.label}}</label>
                {{ form.new_password1 }}
                <small class="text-muted">{{ form.new_password1.errors }}</small>
                <small class="form-text text-muted">{{ form.new_password1.help_text }}</small>
              </div>
              <div class="mb-3 col-md-12">
                <label for="{{ form.new_password2.id_for_label }}">{{form.new_password2.label}}</label>
                {{ form.new_password2 }}
                <small class="text-muted">{{ form.new_password2.errors }}</small>
                <small class="form-text text-muted">{{ form.new_password2.help_text }}</small>
              </div>
            <div class="mt-2">
              <button type="submit" class="btn btn-primary me-2">Simpan</button>
            </div>
          </form>
        </div>
        <!-- /Account -->
      </div>
    </div>
  </div>
</div>
<!-- / Content -->
{% endblock content %}